"""empty message

Revision ID: 673ed45aa672
Revises: 8f9f597aa632
Create Date: 2019-07-14 15:03:13.924904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673ed45aa672'
down_revision = '8f9f597aa632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'age')
    # ### end Alembic commands ###
